language: node_js
node_js:
  - "10.9"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm install -g firebase-tools
  - ng build --prod
  - firebase deploy --project fi17-gfn --token $FIREBASE_TOKEN
