language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
 - echo "Deploy!!"
 - npm install -g firebase-tools
script:
  - npm run lint
  - npm run test:headless
  - npm run build --prod
  - firebase deploy --project fi17-gfn --token $FIREBASE_TOKEN
